spring:
  application:
    name: chat_app
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://jiya:jiya@cluster0.yh9go.mongodb.net/springchat}

server:
  port: ${PORT:8081} 

app:

  frontend:
    url: ${FRONTEND_URL:http://localhost:5173} 
